language: node_js

node_js:
  - 12

jobs:
  include:
    - stage: install
      script:
        - npm install
      skip_cleanup: true
    - stage: test
      script:
        - npm run lint
        - npm run collectCoverage
      skip_cleanup: true
    - stage: compile
      script:
        - npm run build
    # Define the release stage that runs semantic-release
    - stage: release
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        if: branch = master
