language: node_js

node_js:
  - 12

jobs:
  include:
    - stage: install
      script:
        - npm install
    - stage: test
      script:
        - npm run lint
        - npm run collectCoverage
    # Define the release stage that runs semantic-release
    - stage: build & release
      script:
        - npm run build
        - npx semantic-release
      if: branch = master
