name: Extract-Site-Metadata Build & Test

on:
  pull_request:
    branches: [master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16"]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Run ci
        run: npm ci
      - name: Run tests
        run: npm run test && npm run collectCoverage
      - name: Run lint
        run: npm run lint
      - name: Build
        run: npm run build
